### ISSUE TITLE
Exact version of SVGAndroid

### ISSUE THREAD

**Issue by ghost** [raydac/AndroidPirateDice#3]
Could you provide the exact version of SVGAndroid used? I tried HEAD from https://github.com/thinkingcow/svg-android-2, but it's missing SVG.resizePictureAsBitmap

**Comment by raydac** [comment]
sorry, I use my forked version of svg-android, I have published it https://github.com/raydac/svg-android

**Comment by ghost** [comment]
Thanks for pointing out, builds fine now.
