### ISSUE TITLE
[Feature Request] Translations

### ISSUE THREAD

**Issue by rio** [raydac/AndroidPirateDice#4]
Not really an issue with the app. Works very nicely on my Jolla. I've found your app through f-droid and got interested in this board game. The links you've provided to the redesign look very good however my russian isn't that great (read: non existent). I don't know how your russian is or if you've found english versions of the same material. In my case dutch or german would be fine as well, I could then translate it to english and post it on github.

**Comment by raydac** [comment]
Thank you very much for your interest.
I will try to make translation of the game rules to English, I think the game is known only for Russians  and I didn't see any reference of the game in any other language.

**Comment by rio** [comment]
That would be great! Even If you make a rough draft me and my friends can polish it up and make it nicely readable. I've got a 3d printer as well so we could even include 3d models in the repo if we'd want to. I don't know about copyright but we'll deal with that hurdle when we get there.

**Comment by raydac** [comment]
I made some translation of base rules published in the article in 1989
https://github.com/raydac/AndroidPirateDice/blob/master/Docs/BoardGameReferenceEng.pdf

**Comment by rio** [comment]
this is great, I had no idea the gameplay is quite deep with the wind/streams and canons.
Makes me really eager to play it and get the revised materials translated on that forum.
I will try to ask around there, hopefully I can get some help and maybe at least the source files for the stuff those guys made.

**Comment by raydac** [comment]
in game rules published on that forum written mainly the same like in my translation but just with some explanations and variants for more complex game-play
also just for your info, there was another game called "CAPTURE OF COLONIES", developed by the same author, that game-play  was a bit more complex
http://www.translate.ru/siteTranslation/autolink/?direction=re&template=Travels&sourceURL=http://samlib.ru/j/jarow_e/pirates.shtml#conquest

**Comment by rio** [comment]
Oeh that one looks interesting aswell. I've signed up on the forum and asked the original redesigner if he still has the source files that he used. That would make our job quite a bit easier.
